"""
Seed the database with sample opportunity data for demo purposes.
Run: python -m app.db.seed
"""

from __future__ import annotations

import asyncio
import logging

from app.db.database import async_session, init_db
from app.db.models import Opportunity

logger = logging.getLogger(__name__)

SEED_OPPORTUNITIES = [
    {
        "name": "Fulbright Foreign Student Program",
        "organization": "U.S. Department of State",
        "country": "United States",
        "deadline": "2026-10-15",
        "funding_status": "Fully Funded",
        "application_link": "https://foreign.fulbrightonline.org/",
        "opportunity_type": "scholarship",
        "description": "The Fulbright Program offers grants for graduate students, young professionals and artists to study, conduct research, and/or teach English abroad.",
        "eligibility_summary": "Open to citizens of participating countries. Must hold a bachelor's degree. Strong academic record and leadership potential required.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 3.0,
        "requirements": {"language": "English proficiency (TOEFL/IELTS)", "citizenship": "Non-US citizens", "degree": "Bachelor's degree minimum"},
        "tags": ["prestigious", "fully-funded", "usa", "graduate"],
    },
    {
        "name": "DAAD Scholarship",
        "organization": "German Academic Exchange Service",
        "country": "Germany",
        "deadline": "2026-11-15",
        "funding_status": "Fully Funded",
        "application_link": "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
        "opportunity_type": "scholarship",
        "description": "DAAD offers scholarships for international students to pursue Master's and PhD programs at German universities.",
        "eligibility_summary": "Bachelor's degree completed with good grades. Some programs require German language skills.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["engineering", "sciences", "arts", "social sciences"],
        "min_gpa": 3.0,
        "requirements": {"language": "German or English proficiency", "degree": "Bachelor's degree", "experience": "Relevant academic background"},
        "tags": ["germany", "europe", "fully-funded", "graduate"],
    },
    {
        "name": "Chevening Scholarships",
        "organization": "UK Government",
        "country": "United Kingdom",
        "deadline": "2026-11-01",
        "funding_status": "Fully Funded",
        "application_link": "https://www.chevening.org/scholarships/",
        "opportunity_type": "scholarship",
        "description": "Chevening Scholarships are the UK government's global scholarship programme, funded by the Foreign, Commonwealth and Development Office.",
        "eligibility_summary": "Must have at least 2 years of work experience. Leadership potential. Return to home country for 2 years after completion.",
        "degree_levels": ["master"],
        "fields_of_study": ["all"],
        "min_gpa": 2.8,
        "requirements": {"experience": "2+ years work experience", "language": "English proficiency", "commitment": "Return to home country"},
        "tags": ["uk", "prestigious", "fully-funded", "masters-only"],
    },
    {
        "name": "Erasmus Mundus Joint Master Degrees",
        "organization": "European Commission",
        "country": "Europe (Multiple)",
        "deadline": "2027-01-15",
        "funding_status": "Fully Funded",
        "application_link": "https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",
        "opportunity_type": "scholarship",
        "description": "Erasmus Mundus Joint Master Degrees are prestigious, integrated, international study programmes, jointly delivered by an international consortium of higher education institutions.",
        "eligibility_summary": "Open to students worldwide. Must hold a bachelor's degree. Selection based on academic excellence.",
        "degree_levels": ["master"],
        "fields_of_study": ["all"],
        "min_gpa": 3.0,
        "requirements": {"degree": "Bachelor's degree", "language": "English proficiency"},
        "tags": ["europe", "multi-country", "fully-funded", "prestigious"],
    },
    {
        "name": "Google Summer of Code",
        "organization": "Google",
        "country": "Remote / Global",
        "deadline": "2027-04-02",
        "funding_status": "Stipend Provided",
        "application_link": "https://summerofcode.withgoogle.com/",
        "opportunity_type": "internship",
        "description": "Google Summer of Code is a global, online program focused on bringing new contributors into open source software development.",
        "eligibility_summary": "Must be 18+ and eligible to work. Open to beginners and students. Must be new or beginner contributors to open source.",
        "degree_levels": ["bachelor", "master", "phd"],
        "fields_of_study": ["computer science", "software engineering", "information technology"],
        "min_gpa": None,
        "requirements": {"skills": "Programming proficiency", "age": "18+"},
        "tags": ["remote", "tech", "open-source", "stipend", "global"],
    },
    {
        "name": "CERN Summer Student Programme",
        "organization": "CERN",
        "country": "Switzerland",
        "deadline": "2027-01-31",
        "funding_status": "Fully Funded",
        "application_link": "https://home.cern/summer-student-programme",
        "opportunity_type": "summer_school",
        "description": "Spend the summer at CERN working with leading researchers in physics, computing, and engineering.",
        "eligibility_summary": "Undergraduate students in physics, computing, mathematics, or engineering. Must have completed at least 3 years of study.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["physics", "computer science", "engineering", "mathematics"],
        "min_gpa": 3.2,
        "requirements": {"year": "3+ years completed", "field": "STEM fields", "language": "English proficiency"},
        "tags": ["switzerland", "physics", "research", "summer", "prestigious"],
    },
    {
        "name": "MIT MISTI Global Teaching Labs",
        "organization": "Massachusetts Institute of Technology",
        "country": "Multiple Countries",
        "deadline": "2026-09-30",
        "funding_status": "Partially Funded",
        "application_link": "https://misti.mit.edu/global-teaching-labs",
        "opportunity_type": "exchange",
        "description": "MIT students teach STEM subjects in high schools around the world during January term.",
        "eligibility_summary": "MIT students with strong STEM background. Teaching experience preferred.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["all"],
        "min_gpa": 3.0,
        "requirements": {"enrollment": "MIT student", "skills": "Teaching ability"},
        "tags": ["teaching", "exchange", "global", "stem"],
    },
    {
        "name": "Rhodes Scholarship",
        "organization": "Rhodes Trust",
        "country": "United Kingdom",
        "deadline": "2026-10-01",
        "funding_status": "Fully Funded",
        "application_link": "https://www.rhodeshouse.ox.ac.uk/scholarships/",
        "opportunity_type": "fellowship",
        "description": "The Rhodes Scholarship is the oldest and most prestigious international scholarship, enabling outstanding young people to study at the University of Oxford.",
        "eligibility_summary": "Age 19-25 at time of application. Outstanding academic achievement. Leadership and commitment to service.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 3.7,
        "requirements": {"age": "19-25", "academics": "Outstanding record", "leadership": "Demonstrated leadership"},
        "tags": ["oxford", "uk", "prestigious", "fully-funded", "fellowship"],
    },
    {
        "name": "MITACS Globalink Research Internship",
        "organization": "MITACS",
        "country": "Canada",
        "deadline": "2026-09-15",
        "funding_status": "Fully Funded",
        "application_link": "https://www.mitacs.ca/en/programs/globalink/globalink-research-internship",
        "opportunity_type": "research",
        "description": "A competitive initiative for international undergraduates to participate in 12-week research internships at Canadian universities.",
        "eligibility_summary": "Undergraduate students from eligible countries with strong academic records in STEM or social sciences.",
        "degree_levels": ["bachelor"],
        "fields_of_study": ["sciences", "engineering", "social sciences", "humanities"],
        "min_gpa": 3.2,
        "requirements": {"level": "Undergraduate", "country": "Eligible partner countries", "gpa": "Above average"},
        "tags": ["canada", "research", "undergraduate", "summer", "fully-funded"],
    },
    {
        "name": "Schwarzman Scholars Program",
        "organization": "Schwarzman Scholars",
        "country": "China",
        "deadline": "2026-09-15",
        "funding_status": "Fully Funded",
        "application_link": "https://www.schwarzmanscholars.org/",
        "opportunity_type": "fellowship",
        "description": "A highly selective master's program at Tsinghua University in Beijing designed to prepare future leaders for a world in which China plays a major role.",
        "eligibility_summary": "Age 18-28. Bachelor's degree required. Strong leadership record and global perspective.",
        "degree_levels": ["master"],
        "fields_of_study": ["public policy", "economics", "business", "international relations"],
        "min_gpa": 3.5,
        "requirements": {"age": "18-28", "degree": "Bachelor's", "language": "English proficiency"},
        "tags": ["china", "leadership", "fully-funded", "prestigious", "masters"],
    },
    {
        "name": "Japanese Government (MEXT) Scholarship",
        "organization": "Ministry of Education, Japan",
        "country": "Japan",
        "deadline": "2027-04-30",
        "funding_status": "Fully Funded",
        "application_link": "https://www.studyinjapan.go.jp/en/smap-stopj-applications-702.html",
        "opportunity_type": "scholarship",
        "description": "The Japanese Government (MEXT) Scholarship offers international students the opportunity to study at Japanese universities with full financial support.",
        "eligibility_summary": "Under 35 years old for research students. Strong academic record. Willingness to learn Japanese.",
        "degree_levels": ["bachelor", "master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 2.8,
        "requirements": {"age": "Under 35 for research", "nationality": "Non-Japanese", "health": "Good health"},
        "tags": ["japan", "asia", "fully-funded", "all-levels"],
    },
    {
        "name": "Australian Government Research Training Program",
        "organization": "Australian Government",
        "country": "Australia",
        "deadline": "2026-08-31",
        "funding_status": "Fully Funded",
        "application_link": "https://www.education.gov.au/research-training-program",
        "opportunity_type": "research",
        "description": "The RTP provides block grants to higher education providers to support both domestic and overseas students undertaking research doctorate and research master's degrees.",
        "eligibility_summary": "Enrolled or enrolling in a research higher degree. Strong academic and research track record.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 3.3,
        "requirements": {"degree": "Research degree enrollment", "research": "Demonstrated research capability"},
        "tags": ["australia", "research", "phd", "fully-funded"],
    },
    {
        "name": "Swiss Government Excellence Scholarships",
        "organization": "Swiss Confederation",
        "country": "Switzerland",
        "deadline": "2026-12-01",
        "funding_status": "Fully Funded",
        "application_link": "https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html",
        "opportunity_type": "scholarship",
        "description": "The Swiss Government Excellence Scholarships provide postgraduate researchers with the opportunity to pursue research or further studies at a Swiss university.",
        "eligibility_summary": "Master's degree holders for PhD. PhD holders for postdoc. Under 35 years old.",
        "degree_levels": ["phd"],
        "fields_of_study": ["all"],
        "min_gpa": 3.5,
        "requirements": {"degree": "Master's minimum", "age": "Under 35", "research": "Research proposal required"},
        "tags": ["switzerland", "europe", "research", "fully-funded", "phd"],
    },
    {
        "name": "Microsoft Research Internship",
        "organization": "Microsoft",
        "country": "United States",
        "deadline": "Rolling",
        "funding_status": "Paid",
        "application_link": "https://www.microsoft.com/en-us/research/academic-program/research-internship/",
        "opportunity_type": "internship",
        "description": "Research internships at Microsoft Research for PhD students and exceptional Master's students in computer science and related fields.",
        "eligibility_summary": "Currently enrolled in PhD or exceptional Master's program in CS, AI, ML, or related fields.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["computer science", "artificial intelligence", "machine learning"],
        "min_gpa": 3.5,
        "requirements": {"enrollment": "Graduate student", "field": "CS/AI/ML", "skills": "Research publications preferred"},
        "tags": ["usa", "tech", "research", "paid", "ai-ml"],
    },
    {
        "name": "Korea Foundation Global e-School Program",
        "organization": "Korea Foundation",
        "country": "South Korea",
        "deadline": "2027-03-01",
        "funding_status": "Fully Funded",
        "application_link": "https://www.kf.or.kr/",
        "opportunity_type": "exchange",
        "description": "An online education program providing Korean studies courses taught by professors from leading Korean universities to students worldwide.",
        "eligibility_summary": "University students interested in Korean studies. No Korean language requirement for most courses.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["korean studies", "international relations", "asian studies", "humanities"],
        "min_gpa": 2.5,
        "requirements": {"enrollment": "University student", "interest": "Korean studies"},
        "tags": ["korea", "online", "exchange", "cultural-studies"],
    },
    # ──────────────────────────────────────────────
    # SCHOLARSHIPS
    # ──────────────────────────────────────────────
    {
        "name": "Commonwealth Scholarship",
        "organization": "Commonwealth Scholarship Commission",
        "country": "United Kingdom",
        "deadline": "2026-12-01",
        "funding_status": "Fully Funded",
        "application_link": "https://cscuk.fcdo.gov.uk/",
        "opportunity_type": "scholarship",
        "description": "The Commonwealth Scholarship enables talented students from Commonwealth countries to pursue postgraduate study in the UK. It covers tuition, living expenses, and airfare for the duration of the programme.",
        "eligibility_summary": "Citizens of Commonwealth countries. Must hold at least an upper second-class honours degree. Committed to development impact in home country.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 3.3,
        "requirements": {"citizenship": "Commonwealth country citizen", "degree": "Upper second-class honours minimum", "commitment": "Return to home country"},
        "tags": ["uk", "commonwealth", "fully-funded", "graduate", "development"],
    },
    {
        "name": "Australian Awards Scholarship",
        "organization": "Australian Government (DFAT)",
        "country": "Australia",
        "deadline": "2026-04-30",
        "funding_status": "Fully Funded",
        "application_link": "https://www.australiaawards.gov.au/",
        "opportunity_type": "scholarship",
        "description": "Australia Awards Scholarships provide opportunities for people from developing countries to undertake full-time undergraduate or postgraduate study at participating Australian universities. The scholarships cover full tuition fees, return air travel, establishment allowance, and a living allowance.",
        "eligibility_summary": "Citizens of participating developing countries. Must meet academic and English language requirements. Two-year home-country service requirement after graduation.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 2.8,
        "requirements": {"citizenship": "Eligible developing country", "language": "English proficiency (IELTS 6.5+)", "commitment": "Return to home country for 2 years"},
        "tags": ["australia", "fully-funded", "development", "graduate"],
    },
    {
        "name": "Korean Government Scholarship KGSP",
        "organization": "National Institute for International Education (NIIED)",
        "country": "South Korea",
        "deadline": "2026-03-01",
        "funding_status": "Fully Funded",
        "application_link": "https://www.studyinkorea.go.kr/",
        "opportunity_type": "scholarship",
        "description": "The Korean Government Scholarship Program provides international students with opportunities to conduct advanced studies at higher educational institutions in South Korea. It includes a one-year Korean language course, full tuition, monthly stipend, and airfare.",
        "eligibility_summary": "Citizens of countries with diplomatic relations with South Korea. Must hold a relevant degree for the level of study. GPA of 80% or above on a 100-point scale.",
        "degree_levels": ["bachelor", "master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 2.6,
        "requirements": {"age": "Under 25 (bachelor) / Under 40 (graduate)", "citizenship": "Eligible country citizen", "health": "Good physical and mental health"},
        "tags": ["south-korea", "asia", "fully-funded", "all-levels", "korean-language"],
    },
    {
        "name": "Chinese Government Scholarship CSC",
        "organization": "China Scholarship Council",
        "country": "China",
        "deadline": "2026-03-15",
        "funding_status": "Fully Funded",
        "application_link": "https://www.campuschina.org/",
        "opportunity_type": "scholarship",
        "description": "The Chinese Government Scholarship (CSC) supports international students pursuing degrees at Chinese universities across all disciplines. It covers tuition, accommodation, medical insurance, and a monthly stipend.",
        "eligibility_summary": "Non-Chinese citizens with good health. Must hold relevant degrees for the desired level of study. Age limits vary by degree level.",
        "degree_levels": ["bachelor", "master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 2.5,
        "requirements": {"citizenship": "Non-Chinese citizen", "health": "Good health certified by medical exam", "age": "Under 25 (bachelor) / Under 35 (master) / Under 40 (PhD)"},
        "tags": ["china", "asia", "fully-funded", "all-levels"],
    },
    {
        "name": "Turkish Government Scholarship Turkiye Burslari",
        "organization": "Turkiye Burslari (YTB)",
        "country": "Turkey",
        "deadline": "2026-02-20",
        "funding_status": "Fully Funded",
        "application_link": "https://turkiyeburslari.gov.tr/",
        "opportunity_type": "scholarship",
        "description": "Turkiye Burslari is a government-funded scholarship program for international students to study in Turkey at all degree levels. It includes a one-year Turkish language course, tuition, accommodation, monthly stipend, and health insurance.",
        "eligibility_summary": "Open to citizens of all countries. Must meet minimum GPA requirement for the level of study. Cannot be a Turkish citizen or currently studying in Turkey.",
        "degree_levels": ["bachelor", "master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 2.5,
        "requirements": {"gpa": "70% (bachelor) / 75% (graduate)", "age": "Under 21 (bachelor) / Under 30 (master) / Under 35 (PhD)", "citizenship": "Non-Turkish citizen"},
        "tags": ["turkey", "fully-funded", "all-levels", "turkish-language"],
    },
    {
        "name": "Swedish Institute Scholarship",
        "organization": "Swedish Institute",
        "country": "Sweden",
        "deadline": "2026-02-10",
        "funding_status": "Fully Funded",
        "application_link": "https://si.se/en/apply/scholarships/",
        "opportunity_type": "scholarship",
        "description": "The Swedish Institute Scholarships for Global Professionals (SISGP) target future leaders from eligible countries to pursue a master's degree in Sweden. The scholarship covers tuition, living expenses, travel grant, and insurance.",
        "eligibility_summary": "Citizens of eligible countries with at least 3,000 hours of work or volunteer experience. Must have applied to an eligible master's programme in Sweden.",
        "degree_levels": ["master"],
        "fields_of_study": ["all"],
        "min_gpa": 3.0,
        "requirements": {"experience": "3,000+ hours work/volunteer experience", "citizenship": "Eligible country", "language": "English proficiency"},
        "tags": ["sweden", "europe", "fully-funded", "masters-only", "leadership"],
    },
    {
        "name": "Hungary Stipendium Hungaricum",
        "organization": "Tempus Public Foundation",
        "country": "Hungary",
        "deadline": "2026-01-15",
        "funding_status": "Fully Funded",
        "application_link": "https://stipendiumhungaricum.hu/",
        "opportunity_type": "scholarship",
        "description": "Stipendium Hungaricum is a scholarship programme funded by the Hungarian Government offering full scholarships for international students at all degree levels. It covers tuition, accommodation, health insurance, and a monthly stipend.",
        "eligibility_summary": "Citizens of countries with a bilateral agreement with Hungary. Must meet academic requirements for the chosen programme. No Hungarian language requirement for English-taught programmes.",
        "degree_levels": ["bachelor", "master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 2.5,
        "requirements": {"citizenship": "Bilateral agreement country", "language": "English proficiency for English-taught programmes", "health": "Medical fitness certificate"},
        "tags": ["hungary", "europe", "fully-funded", "all-levels"],
    },
    {
        "name": "New Zealand Excellence Awards",
        "organization": "Universities New Zealand",
        "country": "New Zealand",
        "deadline": "2026-10-28",
        "funding_status": "Partially Funded",
        "application_link": "https://www.universitiesnz.ac.nz/",
        "opportunity_type": "scholarship",
        "description": "The New Zealand Excellence Awards provide partial funding for high-achieving international students pursuing postgraduate study in New Zealand. Awards cover a portion of tuition fees at participating universities.",
        "eligibility_summary": "International students with strong academic records applying for postgraduate programmes at New Zealand universities. Must demonstrate leadership potential.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 3.2,
        "requirements": {"degree": "Bachelor's degree minimum", "academics": "Strong academic record", "language": "English proficiency (IELTS 6.5+)"},
        "tags": ["new-zealand", "partial-funding", "graduate", "oceania"],
    },
    {
        "name": "Canada Vanier CGS",
        "organization": "Government of Canada",
        "country": "Canada",
        "deadline": "2026-11-01",
        "funding_status": "Fully Funded",
        "application_link": "https://vanier.gc.ca/",
        "opportunity_type": "scholarship",
        "description": "The Vanier Canada Graduate Scholarships (Vanier CGS) program attracts and retains world-class doctoral students by supporting those who demonstrate leadership skills and a high standard of scholarly achievement. It provides $50,000 per year for three years.",
        "eligibility_summary": "Nominated by a Canadian university. Must be pursuing or about to pursue a doctoral degree. Demonstrated academic excellence and leadership.",
        "degree_levels": ["phd"],
        "fields_of_study": ["all"],
        "min_gpa": 3.5,
        "requirements": {"degree": "Pursuing or about to start PhD", "nomination": "Must be nominated by a Canadian institution", "leadership": "Demonstrated leadership"},
        "tags": ["canada", "phd", "fully-funded", "prestigious", "research"],
    },
    {
        "name": "Gates Cambridge Scholarship",
        "organization": "Gates Cambridge Trust",
        "country": "United Kingdom",
        "deadline": "2026-12-04",
        "funding_status": "Fully Funded",
        "application_link": "https://www.gatescambridge.org/",
        "opportunity_type": "scholarship",
        "description": "The Gates Cambridge Scholarship is awarded to outstanding applicants from countries outside the UK to pursue a full-time postgraduate degree at the University of Cambridge. It covers full cost of study including tuition, living allowance, and airfare.",
        "eligibility_summary": "Applicants from outside the UK applying to a full-time postgraduate programme at Cambridge. Outstanding academic record and commitment to improving the lives of others.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 3.7,
        "requirements": {"citizenship": "Non-UK citizen", "academics": "Outstanding academic record", "commitment": "Commitment to social impact"},
        "tags": ["uk", "cambridge", "prestigious", "fully-funded", "graduate"],
    },
    {
        "name": "Orange Knowledge Programme",
        "organization": "Nuffic",
        "country": "Netherlands",
        "deadline": "2026-09-30",
        "funding_status": "Fully Funded",
        "application_link": "https://www.nuffic.nl/en/subjects/orange-knowledge-programme",
        "opportunity_type": "scholarship",
        "description": "The Orange Knowledge Programme offers fellowships for mid-career professionals from eligible countries to pursue short courses and master's programmes in the Netherlands. It aims to strengthen organisations in developing countries.",
        "eligibility_summary": "Mid-career professionals from OKP partner countries with at least two years of work experience. Must have employer endorsement and commitment to apply learning in home country.",
        "degree_levels": ["master"],
        "fields_of_study": ["development studies", "agriculture", "health", "water management", "environment"],
        "min_gpa": 2.8,
        "requirements": {"experience": "2+ years relevant work experience", "citizenship": "OKP partner country", "employer": "Employer endorsement letter"},
        "tags": ["netherlands", "europe", "fully-funded", "development", "mid-career"],
    },
    # ──────────────────────────────────────────────
    # RESEARCH
    # ──────────────────────────────────────────────
    {
        "name": "Max Planck Research Internship",
        "organization": "Max Planck Society",
        "country": "Germany",
        "deadline": "2026-11-30",
        "funding_status": "Fully Funded",
        "application_link": "https://www.mpg.de/internships",
        "opportunity_type": "research",
        "description": "Max Planck Institutes across Germany offer research internships for talented international students in a wide range of scientific disciplines. Interns work alongside world-leading researchers on cutting-edge projects.",
        "eligibility_summary": "Undergraduate or master's students in relevant scientific fields. Strong academic record and genuine interest in research required.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["sciences", "engineering", "computer science", "physics", "biology", "chemistry"],
        "min_gpa": 3.2,
        "requirements": {"level": "Undergraduate or Master's student", "field": "Relevant STEM discipline", "language": "English proficiency"},
        "tags": ["germany", "research", "fully-funded", "stem", "prestigious"],
    },
    {
        "name": "KAIST Research Internship",
        "organization": "Korea Advanced Institute of Science and Technology",
        "country": "South Korea",
        "deadline": "2026-03-31",
        "funding_status": "Fully Funded",
        "application_link": "https://www.kaist.ac.kr/",
        "opportunity_type": "research",
        "description": "KAIST offers research internships for international students to work with top faculty in science and technology. Interns receive a stipend, accommodation, and exposure to world-class research facilities.",
        "eligibility_summary": "Undergraduate or master's students with strong academic records in science, engineering, or technology. Must be enrolled in a degree programme outside South Korea.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["engineering", "computer science", "sciences", "mathematics"],
        "min_gpa": 3.0,
        "requirements": {"enrollment": "Currently enrolled outside South Korea", "field": "STEM discipline", "language": "English proficiency"},
        "tags": ["south-korea", "research", "fully-funded", "stem", "asia"],
    },
    {
        "name": "ETH Zurich Summer Research Fellowship",
        "organization": "ETH Zurich",
        "country": "Switzerland",
        "deadline": "2026-12-15",
        "funding_status": "Fully Funded",
        "application_link": "https://inf.ethz.ch/studies/summer-research-fellowship.html",
        "opportunity_type": "research",
        "description": "The ETH Zurich Summer Research Fellowship provides students with the opportunity to conduct research at one of the world's top technical universities. Fellows receive a stipend, housing support, and mentorship from leading academics.",
        "eligibility_summary": "Undergraduate or master's students in computer science or related fields with excellent academic records. Must be enrolled at a university outside Switzerland.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["computer science", "mathematics", "engineering", "physics"],
        "min_gpa": 3.5,
        "requirements": {"enrollment": "University outside Switzerland", "field": "CS or related field", "academics": "Excellent academic record"},
        "tags": ["switzerland", "research", "fully-funded", "summer", "computer-science"],
    },
    {
        "name": "KAUST Research",
        "organization": "King Abdullah University of Science and Technology",
        "country": "Saudi Arabia",
        "deadline": "Rolling",
        "funding_status": "Fully Funded",
        "application_link": "https://www.kaust.edu.sa/",
        "opportunity_type": "research",
        "description": "KAUST provides fully funded research opportunities for graduate students and visiting researchers in STEM fields. The programme offers world-class research facilities, a generous stipend, and free housing.",
        "eligibility_summary": "Master's or PhD students in STEM fields with strong academic backgrounds. All nationalities are welcome to apply on a rolling basis.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["engineering", "sciences", "computer science", "environmental science"],
        "min_gpa": 3.0,
        "requirements": {"degree": "Master's or PhD enrollment", "field": "STEM discipline", "language": "English proficiency"},
        "tags": ["saudi-arabia", "research", "fully-funded", "stem", "rolling-deadline"],
    },
    {
        "name": "NTU Singapore Research Internship",
        "organization": "Nanyang Technological University",
        "country": "Singapore",
        "deadline": "2026-02-28",
        "funding_status": "Partially Funded",
        "application_link": "https://www.ntu.edu.sg/",
        "opportunity_type": "research",
        "description": "Nanyang Technological University offers research internship positions for international students to work alongside faculty in cutting-edge research labs. Partial funding through stipends may be available depending on the department.",
        "eligibility_summary": "Undergraduate or master's students enrolled in relevant science, engineering, or technology programmes. Strong academic record required.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["engineering", "computer science", "sciences", "business"],
        "min_gpa": 3.0,
        "requirements": {"enrollment": "Enrolled in a degree programme", "field": "Relevant discipline", "language": "English proficiency"},
        "tags": ["singapore", "asia", "research", "partial-funding", "stem"],
    },
    {
        "name": "Oxford Research Internship",
        "organization": "University of Oxford",
        "country": "United Kingdom",
        "deadline": "2026-01-31",
        "funding_status": "Partially Funded",
        "application_link": "https://www.ox.ac.uk/",
        "opportunity_type": "research",
        "description": "The University of Oxford offers selective research internship placements across its departments for international undergraduate and master's students. Funding varies by department and project.",
        "eligibility_summary": "Undergraduate or master's students with strong academic records. Specific eligibility depends on the host department and research group.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["all"],
        "min_gpa": 3.5,
        "requirements": {"academics": "Strong academic record", "language": "English proficiency", "application": "Research statement required"},
        "tags": ["uk", "oxford", "research", "partial-funding", "prestigious"],
    },
    {
        "name": "IIT Bombay Research Internship",
        "organization": "Indian Institute of Technology Bombay",
        "country": "India",
        "deadline": "2026-03-15",
        "funding_status": "Partially Funded",
        "application_link": "https://www.iitb.ac.in/",
        "opportunity_type": "research",
        "description": "IIT Bombay offers research internships for international students to collaborate with faculty on research projects across engineering, sciences, and technology. Partial funding may be available through specific programmes.",
        "eligibility_summary": "Undergraduate or master's students in relevant fields with a strong academic background. Prior research experience is preferred but not mandatory.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["engineering", "computer science", "sciences", "mathematics"],
        "min_gpa": 3.0,
        "requirements": {"enrollment": "Currently enrolled in a degree programme", "field": "STEM discipline", "language": "English proficiency"},
        "tags": ["india", "asia", "research", "partial-funding", "stem"],
    },
    {
        "name": "RIKEN Research Internship",
        "organization": "RIKEN",
        "country": "Japan",
        "deadline": "2026-04-15",
        "funding_status": "Fully Funded",
        "application_link": "https://www.riken.jp/en/careers/students/irs/",
        "opportunity_type": "research",
        "description": "RIKEN's International Research Student programme enables international graduate students to conduct research at one of Japan's largest and most comprehensive research institutions. It provides a stipend, commuting allowance, and housing support.",
        "eligibility_summary": "Master's or PhD students enrolled at a university outside Japan with a focus on natural sciences or engineering. Must be recommended by a RIKEN lab head.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["physics", "chemistry", "biology", "engineering", "computer science"],
        "min_gpa": 3.2,
        "requirements": {"enrollment": "Graduate student outside Japan", "recommendation": "RIKEN lab head endorsement", "field": "Natural sciences or engineering"},
        "tags": ["japan", "research", "fully-funded", "stem", "prestigious"],
    },
    # ──────────────────────────────────────────────
    # INTERNSHIPS
    # ──────────────────────────────────────────────
    {
        "name": "United Nations Internship",
        "organization": "United Nations",
        "country": "Global / Remote",
        "deadline": "Rolling",
        "funding_status": "Self Funded",
        "application_link": "https://careers.un.org/lbw/home.aspx",
        "opportunity_type": "internship",
        "description": "The United Nations offers internship opportunities across its offices and agencies worldwide for students and recent graduates. Interns gain first-hand exposure to the UN's work in international development, peacekeeping, and human rights.",
        "eligibility_summary": "Enrolled in a graduate or final year of an undergraduate programme, or a recent graduate. Must be fluent in at least one UN official language.",
        "degree_levels": ["bachelor", "master", "phd"],
        "fields_of_study": ["international relations", "law", "political science", "economics", "development studies", "all"],
        "min_gpa": None,
        "requirements": {"enrollment": "Graduate or final-year undergraduate", "language": "One UN official language", "age": "18+"},
        "tags": ["global", "remote", "international-org", "self-funded", "rolling-deadline"],
    },
    {
        "name": "UNICEF Internship",
        "organization": "UNICEF",
        "country": "Global / Remote",
        "deadline": "Rolling",
        "funding_status": "Self Funded",
        "application_link": "https://www.unicef.org/careers/internships",
        "opportunity_type": "internship",
        "description": "UNICEF internships allow students and recent graduates to gain practical experience in areas such as child protection, education, health, and communication. Positions are available at headquarters and field offices worldwide.",
        "eligibility_summary": "Enrolled in an undergraduate, graduate, or PhD programme, or a recent graduate. Must be at least 18 years old and proficient in at least one working language of the duty station.",
        "degree_levels": ["bachelor", "master", "phd"],
        "fields_of_study": ["public health", "education", "social sciences", "communications", "international relations"],
        "min_gpa": None,
        "requirements": {"age": "18+", "enrollment": "Enrolled or recent graduate", "language": "Duty station language proficiency"},
        "tags": ["global", "remote", "unicef", "self-funded", "rolling-deadline", "development"],
    },
    {
        "name": "World Bank Internship",
        "organization": "World Bank Group",
        "country": "United States",
        "deadline": "2026-10-31",
        "funding_status": "Partially Funded",
        "application_link": "https://www.worldbank.org/en/about/careers/programs-and-internships",
        "opportunity_type": "internship",
        "description": "The World Bank Group Internship Program offers highly motivated individuals the opportunity to be exposed to the mission and work of the World Bank. Interns receive a salary and may be assigned to offices in Washington, D.C. or country offices.",
        "eligibility_summary": "Enrolled in a graduate programme (master's or PhD). Must have completed at least one year of graduate study. Fluency in English required.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["economics", "finance", "development studies", "public policy", "social sciences", "engineering"],
        "min_gpa": 3.0,
        "requirements": {"enrollment": "Graduate student (1+ year completed)", "language": "Fluent in English", "skills": "Relevant analytical skills"},
        "tags": ["usa", "development", "finance", "partial-funding", "prestigious"],
    },
    {
        "name": "European Parliament Internship",
        "organization": "European Parliament",
        "country": "Belgium",
        "deadline": "2026-09-01",
        "funding_status": "Partially Funded",
        "application_link": "https://www.europarl.europa.eu/about-parliament/en/work-with-parliament/traineeships",
        "opportunity_type": "internship",
        "description": "The European Parliament offers paid traineeships (Schuman Traineeships) for university graduates interested in gaining insight into the work of the European Parliament. Trainees work in Brussels or Luxembourg for five months.",
        "eligibility_summary": "University graduates with a degree completed before the start of the traineeship. Must be a citizen of an EU member state or candidate country. Proficiency in at least two EU languages.",
        "degree_levels": ["master"],
        "fields_of_study": ["law", "political science", "international relations", "economics", "communications"],
        "min_gpa": None,
        "requirements": {"degree": "University degree", "citizenship": "EU member or candidate country", "language": "Two EU languages"},
        "tags": ["belgium", "europe", "politics", "partial-funding", "eu"],
    },
    {
        "name": "NASA Internship",
        "organization": "National Aeronautics and Space Administration",
        "country": "United States",
        "deadline": "2026-03-01",
        "funding_status": "Partially Funded",
        "application_link": "https://intern.nasa.gov/",
        "opportunity_type": "internship",
        "description": "NASA internships provide students with unique opportunities to participate in cutting-edge research, engineering, and mission operations across NASA centres. Interns receive a stipend and work alongside NASA scientists and engineers.",
        "eligibility_summary": "US citizens enrolled full-time in an accredited educational institution. Must be at least 16 years old. GPA of 3.0 or higher on a 4.0 scale.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["engineering", "computer science", "physics", "mathematics", "aerospace"],
        "min_gpa": 3.0,
        "requirements": {"citizenship": "US citizen", "enrollment": "Full-time student", "gpa": "3.0+ on 4.0 scale"},
        "tags": ["usa", "space", "stem", "partial-funding", "prestigious"],
    },
    {
        "name": "Asian Development Bank Internship",
        "organization": "Asian Development Bank",
        "country": "Philippines",
        "deadline": "2026-09-30",
        "funding_status": "Partially Funded",
        "application_link": "https://www.adb.org/work-with-us/careers/internship-program",
        "opportunity_type": "internship",
        "description": "The ADB Internship Program provides an opportunity for graduate students from ADB member countries to gain practical experience in development finance and policy. Interns are based at ADB headquarters in Manila.",
        "eligibility_summary": "Enrolled in a master's or PhD programme at an accredited institution. Must be a national of an ADB member country. Under 32 years of age at the time of application.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["economics", "finance", "development studies", "public policy", "environmental science"],
        "min_gpa": 3.0,
        "requirements": {"enrollment": "Graduate student", "citizenship": "ADB member country", "age": "Under 32"},
        "tags": ["philippines", "asia", "development", "finance", "partial-funding"],
    },
    {
        "name": "IBM Research Internship",
        "organization": "IBM Research",
        "country": "United States",
        "deadline": "Rolling",
        "funding_status": "Partially Funded",
        "application_link": "https://research.ibm.com/careers",
        "opportunity_type": "internship",
        "description": "IBM Research internships allow graduate students to work on pioneering research in AI, quantum computing, cloud, and systems. Interns collaborate with world-class scientists and have access to state-of-the-art facilities.",
        "eligibility_summary": "Currently enrolled in a master's or PhD programme in computer science, electrical engineering, or related fields. Strong publication record preferred.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["computer science", "artificial intelligence", "quantum computing", "electrical engineering"],
        "min_gpa": 3.3,
        "requirements": {"enrollment": "Graduate student (MS/PhD)", "field": "CS, EE, or related", "research": "Publications preferred"},
        "tags": ["usa", "tech", "research", "ai", "quantum", "rolling-deadline"],
    },
    {
        "name": "Meta University Program",
        "organization": "Meta Platforms",
        "country": "United States",
        "deadline": "2026-01-15",
        "funding_status": "Partially Funded",
        "application_link": "https://www.metacareers.com/careerprograms/students/",
        "opportunity_type": "internship",
        "description": "Meta's university internship programme provides students with hands-on experience in software engineering, data science, and product design at one of the world's largest tech companies. Interns receive competitive compensation and mentorship.",
        "eligibility_summary": "Currently enrolled in a bachelor's or master's programme in computer science, engineering, or a related field. Must be authorised to work in the US.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["computer science", "software engineering", "data science", "design"],
        "min_gpa": 3.0,
        "requirements": {"enrollment": "Enrolled in relevant degree programme", "authorization": "US work authorisation", "skills": "Programming proficiency"},
        "tags": ["usa", "tech", "paid", "software-engineering", "meta"],
    },
    # ──────────────────────────────────────────────
    # FELLOWSHIPS
    # ──────────────────────────────────────────────
    {
        "name": "Hubert Humphrey Fellowship",
        "organization": "U.S. Department of State",
        "country": "United States",
        "deadline": "2026-10-01",
        "funding_status": "Fully Funded",
        "application_link": "https://www.humphreyfellowship.org/",
        "opportunity_type": "fellowship",
        "description": "The Hubert H. Humphrey Fellowship Program brings accomplished mid-career professionals from designated countries to the United States for a year of non-degree graduate-level study, leadership development, and professional enrichment.",
        "eligibility_summary": "Mid-career professionals with at least five years of substantial experience. Strong commitment to public service. Must return to home country after the fellowship.",
        "degree_levels": ["master"],
        "fields_of_study": ["public policy", "public health", "education", "law", "journalism", "agriculture"],
        "min_gpa": None,
        "requirements": {"experience": "5+ years professional experience", "commitment": "Return to home country", "language": "English proficiency"},
        "tags": ["usa", "fellowship", "fully-funded", "mid-career", "leadership"],
    },
    {
        "name": "Aga Khan Foundation Fellowship",
        "organization": "Aga Khan Foundation",
        "country": "Global",
        "deadline": "2026-03-31",
        "funding_status": "Fully Funded",
        "application_link": "https://www.akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme",
        "opportunity_type": "fellowship",
        "description": "The Aga Khan Foundation International Scholarship Programme provides a limited number of scholarships each year for postgraduate studies to outstanding students from select developing countries who have no other means of financing their studies.",
        "eligibility_summary": "Citizens of eligible developing countries with strong academic records. Must demonstrate financial need and commitment to development in home country.",
        "degree_levels": ["master"],
        "fields_of_study": ["all"],
        "min_gpa": 3.0,
        "requirements": {"citizenship": "Eligible developing country", "financial_need": "Demonstrated financial need", "commitment": "Development impact in home country"},
        "tags": ["global", "fellowship", "fully-funded", "development", "need-based"],
    },
    {
        "name": "Atlantic Fellows",
        "organization": "Atlantic Institute",
        "country": "Global",
        "deadline": "2026-01-15",
        "funding_status": "Fully Funded",
        "application_link": "https://atlanticfellows.org/",
        "opportunity_type": "fellowship",
        "description": "Atlantic Fellows programmes support exceptional individuals from around the world working to tackle inequity in health, racial equity, social and economic equity, and brain health. Fellows join a lifelong community of changemakers.",
        "eligibility_summary": "Mid-career leaders with demonstrated commitment to advancing equity and social justice. Programme-specific eligibility criteria apply to each of the seven fellowship programmes.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["public health", "social sciences", "law", "public policy", "economics"],
        "min_gpa": None,
        "requirements": {"experience": "Mid-career professional", "commitment": "Advancing equity and social justice", "leadership": "Demonstrated impact"},
        "tags": ["global", "fellowship", "fully-funded", "equity", "leadership"],
    },
    {
        "name": "Obama Foundation Fellowship",
        "organization": "Obama Foundation",
        "country": "United States",
        "deadline": "Rolling",
        "funding_status": "Fully Funded",
        "application_link": "https://www.obama.org/programs/fellows/",
        "opportunity_type": "fellowship",
        "description": "The Obama Foundation Fellows program supports rising civic leaders from around the world who are working to solve problems in their communities. Fellows receive two years of support including leadership development, a stipend, and access to a global network.",
        "eligibility_summary": "Emerging civic leaders with a proven track record of community impact. Must be working on civic engagement, public service, or community organising.",
        "degree_levels": ["master"],
        "fields_of_study": ["public policy", "social sciences", "education", "community development"],
        "min_gpa": None,
        "requirements": {"experience": "Community impact track record", "commitment": "Civic engagement focus", "leadership": "Demonstrated civic leadership"},
        "tags": ["usa", "fellowship", "fully-funded", "civic-leadership", "rolling-deadline"],
    },
    {
        "name": "AAUW International Fellowship",
        "organization": "American Association of University Women",
        "country": "United States",
        "deadline": "2026-11-15",
        "funding_status": "Fully Funded",
        "application_link": "https://www.aauw.org/resources/programs/fellowships-grants/current-opportunities/international/",
        "opportunity_type": "fellowship",
        "description": "AAUW International Fellowships are awarded for full-time study or research in the United States to women who are not US citizens or permanent residents. The fellowship supports women pursuing advanced academic work and original research.",
        "eligibility_summary": "Women who are not US citizens or permanent residents. Must hold an academic degree equivalent to a US bachelor's degree. Must be pursuing full-time study or research in the US.",
        "degree_levels": ["master", "phd"],
        "fields_of_study": ["all"],
        "min_gpa": 3.0,
        "requirements": {"gender": "Women only", "citizenship": "Non-US citizen", "degree": "Bachelor's degree equivalent minimum"},
        "tags": ["usa", "fellowship", "fully-funded", "women", "research"],
    },
    # ──────────────────────────────────────────────
    # EXCHANGE
    # ──────────────────────────────────────────────
    {
        "name": "Global UGRAD Pakistan",
        "organization": "U.S. Department of State / IREX",
        "country": "United States",
        "deadline": "2026-11-01",
        "funding_status": "Fully Funded",
        "application_link": "https://pk.usembassy.gov/education-culture/ugrad/",
        "opportunity_type": "exchange",
        "description": "The Global Undergraduate Exchange Program (Global UGRAD) provides one semester of non-degree academic study at a US college or university for undergraduate students from Pakistan. It covers tuition, housing, meals, and round-trip airfare.",
        "eligibility_summary": "Pakistani undergraduate students enrolled in a bachelor's programme with at least one semester remaining after the exchange. Strong academic record and leadership potential.",
        "degree_levels": ["bachelor"],
        "fields_of_study": ["all"],
        "min_gpa": 2.8,
        "requirements": {"citizenship": "Pakistani citizen", "enrollment": "Enrolled in a bachelor's programme", "language": "English proficiency (TOEFL/IELTS)"},
        "tags": ["usa", "exchange", "fully-funded", "undergraduate", "pakistan"],
    },
    {
        "name": "YES Exchange Program",
        "organization": "U.S. Department of State",
        "country": "United States",
        "deadline": "2026-10-01",
        "funding_status": "Fully Funded",
        "application_link": "https://www.yes-abroad.org/",
        "opportunity_type": "exchange",
        "description": "The Kennedy-Lugar Youth Exchange and Study (YES) program provides scholarships for high school students and recent graduates from countries with significant Muslim populations to spend one academic year in the United States. It promotes mutual understanding between cultures.",
        "eligibility_summary": "Students aged 15–17 from eligible countries with significant Muslim populations. Must demonstrate maturity, adaptability, and leadership qualities.",
        "degree_levels": ["bachelor"],
        "fields_of_study": ["all"],
        "min_gpa": 2.5,
        "requirements": {"age": "15-17 years old", "citizenship": "Eligible country", "maturity": "Demonstrated adaptability"},
        "tags": ["usa", "exchange", "fully-funded", "high-school", "cultural-exchange"],
    },
    {
        "name": "Erasmus+ Exchange",
        "organization": "European Commission",
        "country": "Europe (Multiple)",
        "deadline": "2026-02-01",
        "funding_status": "Fully Funded",
        "application_link": "https://erasmus-plus.ec.europa.eu/",
        "opportunity_type": "exchange",
        "description": "Erasmus+ supports student exchange across European universities, enabling students to study abroad for 3 to 12 months at a partner institution. It covers travel costs, living expenses, and tuition fee waivers.",
        "eligibility_summary": "Students enrolled at an Erasmus+ participating institution. Must have completed at least the first year of study. Open to bachelor's and master's students.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["all"],
        "min_gpa": 2.5,
        "requirements": {"enrollment": "Erasmus+ participating institution", "year": "Completed first year of study", "language": "Host country language or English"},
        "tags": ["europe", "exchange", "fully-funded", "multi-country", "semester-abroad"],
    },
    {
        "name": "DAAD RISE Germany",
        "organization": "German Academic Exchange Service",
        "country": "Germany",
        "deadline": "2026-02-01",
        "funding_status": "Fully Funded",
        "application_link": "https://www.daad.de/rise/en/",
        "opportunity_type": "exchange",
        "description": "DAAD RISE (Research Internships in Science and Engineering) offers summer internships in Germany for undergraduate students from North America, the UK, and Ireland. Interns work with doctoral students at top German universities and research institutions.",
        "eligibility_summary": "Undergraduate students enrolled in biology, chemistry, physics, earth sciences, engineering, or a closely related field at a university in North America, UK, or Ireland.",
        "degree_levels": ["bachelor"],
        "fields_of_study": ["biology", "chemistry", "physics", "engineering", "earth sciences"],
        "min_gpa": 3.0,
        "requirements": {"enrollment": "Undergraduate in North America, UK, or Ireland", "field": "STEM discipline", "language": "English (German helpful but not required)"},
        "tags": ["germany", "exchange", "fully-funded", "summer", "stem", "undergraduate"],
    },
    # ──────────────────────────────────────────────
    # SUMMER SCHOOLS
    # ──────────────────────────────────────────────
    {
        "name": "Harvard Summer School",
        "organization": "Harvard University",
        "country": "United States",
        "deadline": "2026-04-15",
        "funding_status": "Self Funded",
        "application_link": "https://summer.harvard.edu/",
        "opportunity_type": "summer_school",
        "description": "Harvard Summer School offers over 450 courses across a wide range of disciplines for visiting undergraduates, graduate students, and professionals. Participants study alongside Harvard students and access world-class faculty and campus resources.",
        "eligibility_summary": "Open to undergraduate and graduate students from any institution worldwide, as well as working professionals. Must demonstrate English proficiency and academic readiness.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["all"],
        "min_gpa": 2.8,
        "requirements": {"enrollment": "Current student or professional", "language": "English proficiency", "application": "Transcript and personal statement"},
        "tags": ["usa", "summer-school", "self-funded", "harvard", "prestigious"],
    },
    {
        "name": "Oxford Summer Programme",
        "organization": "University of Oxford",
        "country": "United Kingdom",
        "deadline": "2026-04-30",
        "funding_status": "Self Funded",
        "application_link": "https://www.ox.ac.uk/admissions/undergraduate/colleges/summer-schools",
        "opportunity_type": "summer_school",
        "description": "Oxford Summer Programmes provide intensive academic courses in the historic setting of the University of Oxford. Participants engage with Oxford's tutorial-style teaching and access college facilities during the summer.",
        "eligibility_summary": "Open to undergraduate and graduate students from any accredited institution. Must demonstrate academic ability and English proficiency.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["all"],
        "min_gpa": 3.0,
        "requirements": {"enrollment": "Current student at accredited institution", "language": "English proficiency", "academics": "Good academic standing"},
        "tags": ["uk", "summer-school", "self-funded", "oxford", "prestigious"],
    },
    {
        "name": "ETH Zurich Summer School",
        "organization": "ETH Zurich",
        "country": "Switzerland",
        "deadline": "2026-03-01",
        "funding_status": "Partially Funded",
        "application_link": "https://ethz.ch/en/studies/non-degree-courses/summer-winter-schools.html",
        "opportunity_type": "summer_school",
        "description": "ETH Zurich Summer Schools cover a range of topics in science, technology, and innovation. Select programmes offer partial fee waivers or travel grants for students from partner institutions.",
        "eligibility_summary": "Undergraduate and graduate students with a background in relevant STEM fields. Specific programme prerequisites may apply.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["engineering", "computer science", "sciences", "mathematics", "architecture"],
        "min_gpa": 3.0,
        "requirements": {"enrollment": "Current student in relevant field", "language": "English proficiency", "prerequisites": "Programme-specific"},
        "tags": ["switzerland", "summer-school", "partial-funding", "stem", "europe"],
    },
    {
        "name": "LSE Summer School",
        "organization": "London School of Economics and Political Science",
        "country": "United Kingdom",
        "deadline": "2026-05-01",
        "funding_status": "Self Funded",
        "application_link": "https://www.lse.ac.uk/study-at-lse/Summer-Schools",
        "opportunity_type": "summer_school",
        "description": "The LSE Summer School offers over 80 three-week courses in accounting, finance, law, international relations, management, and more. It attracts students and professionals from over 130 countries.",
        "eligibility_summary": "Open to undergraduate students who have completed at least one year of study, graduate students, and working professionals. English proficiency required.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["economics", "finance", "law", "international relations", "management", "social sciences"],
        "min_gpa": None,
        "requirements": {"enrollment": "Completed at least one year of undergraduate study", "language": "English proficiency", "age": "18+"},
        "tags": ["uk", "summer-school", "self-funded", "social-sciences", "finance"],
    },
    {
        "name": "MIT Professional Education Summer",
        "organization": "Massachusetts Institute of Technology",
        "country": "United States",
        "deadline": "2026-05-15",
        "funding_status": "Self Funded",
        "application_link": "https://professional.mit.edu/programs/summer-programs",
        "opportunity_type": "summer_school",
        "description": "MIT Professional Education Summer Programs offer intensive courses for advanced undergraduate students, graduate students, and professionals in technology, engineering, and innovation. Participants learn from MIT faculty and access MIT's facilities.",
        "eligibility_summary": "Advanced undergraduate students, graduate students, and working professionals with backgrounds in relevant technical fields. No formal admission process for most courses.",
        "degree_levels": ["bachelor", "master"],
        "fields_of_study": ["engineering", "computer science", "data science", "artificial intelligence", "innovation"],
        "min_gpa": None,
        "requirements": {"background": "Relevant technical background", "language": "English proficiency", "age": "18+"},
        "tags": ["usa", "summer-school", "self-funded", "mit", "tech", "professional"],
    },
]


async def seed_database():
    """Insert seed opportunities into the database."""
    await init_db()

    async with async_session() as session:
        # Check if data already exists and re-seed if below threshold
        from sqlalchemy import select, func
        result = await session.execute(select(func.count(Opportunity.id)))
        count = result.scalar()

        if count >= 50:
            logger.info(f"Database already has {count} opportunities (≥50). Skipping seed.")
            return

        if count > 0:
            logger.info(f"Database has only {count} opportunities (<50). Clearing and re-seeding…")
            await session.execute(Opportunity.__table__.delete())
            await session.flush()

        for data in SEED_OPPORTUNITIES:
            opp = Opportunity(**data)
            session.add(opp)

        await session.commit()
        logger.info(f"✅ Seeded {len(SEED_OPPORTUNITIES)} opportunities into the database.")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(seed_database())
